version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: devops/backend/Dockerfile
    ports:
      - "8000:8000"
    command: python3 backend/manage.py runserver 0.0.0.0:8000
